service: socials-media

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: x86_64
  stage: production
  region: ap-southeast-2
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 15
  

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline